// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: block.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBlock = `-- name: CreateBlock :exec
INSERT INTO blocks (id, profile_id, type, content, position, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateBlockParams struct {
	ID        uuid.UUID `json:"id"`
	ProfileID uuid.UUID `json:"profile_id"`
	Type      string    `json:"type"`
	Content   []byte    `json:"content"`
	Position  int32     `json:"position"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock,
		arg.ID,
		arg.ProfileID,
		arg.Type,
		arg.Content,
		arg.Position,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks WHERE id = $1 AND profile_id = $2
`

type DeleteBlockParams struct {
	ID        uuid.UUID `json:"id"`
	ProfileID uuid.UUID `json:"profile_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.ID, arg.ProfileID)
	return err
}

const incrementBlockClick = `-- name: IncrementBlockClick :exec
UPDATE blocks SET click_count = click_count + 1 WHERE id = $1
`

func (q *Queries) IncrementBlockClick(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementBlockClick, id)
	return err
}

const listActiveBlocksByProfile = `-- name: ListActiveBlocksByProfile :many
SELECT id, profile_id, type, content, position, is_active, click_count, created_at, updated_at FROM blocks WHERE profile_id = $1 AND is_active = true ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListActiveBlocksByProfile(ctx context.Context, profileID uuid.UUID) ([]Block, error) {
	rows, err := q.db.Query(ctx, listActiveBlocksByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Type,
			&i.Content,
			&i.Position,
			&i.IsActive,
			&i.ClickCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksByProfile = `-- name: ListBlocksByProfile :many
SELECT id, profile_id, type, content, position, is_active, click_count, created_at, updated_at FROM blocks WHERE profile_id = $1 ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListBlocksByProfile(ctx context.Context, profileID uuid.UUID) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocksByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Type,
			&i.Content,
			&i.Position,
			&i.IsActive,
			&i.ClickCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlock = `-- name: UpdateBlock :exec
UPDATE blocks
SET type = $2, content = $3, is_active = $4, updated_at = $5
WHERE id = $1 AND profile_id = $6
`

type UpdateBlockParams struct {
	ID        uuid.UUID `json:"id"`
	Type      string    `json:"type"`
	Content   []byte    `json:"content"`
	IsActive  bool      `json:"is_active"`
	UpdatedAt time.Time `json:"updated_at"`
	ProfileID uuid.UUID `json:"profile_id"`
}

func (q *Queries) UpdateBlock(ctx context.Context, arg UpdateBlockParams) error {
	_, err := q.db.Exec(ctx, updateBlock,
		arg.ID,
		arg.Type,
		arg.Content,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ProfileID,
	)
	return err
}

const updateBlockPosition = `-- name: UpdateBlockPosition :exec
UPDATE blocks SET position = $2, updated_at = $3 WHERE id = $1 AND profile_id = $4
`

type UpdateBlockPositionParams struct {
	ID        uuid.UUID `json:"id"`
	Position  int32     `json:"position"`
	UpdatedAt time.Time `json:"updated_at"`
	ProfileID uuid.UUID `json:"profile_id"`
}

func (q *Queries) UpdateBlockPosition(ctx context.Context, arg UpdateBlockPositionParams) error {
	_, err := q.db.Exec(ctx, updateBlockPosition,
		arg.ID,
		arg.Position,
		arg.UpdatedAt,
		arg.ProfileID,
	)
	return err
}
