// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (id, user_id, username, display_name, bio, avatar_url, appearance, is_published, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateProfileParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
	Bio         string    `json:"bio"`
	AvatarUrl   string    `json:"avatar_url"`
	Appearance  []byte    `json:"appearance"`
	IsPublished bool      `json:"is_published"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.Exec(ctx, createProfile,
		arg.ID,
		arg.UserID,
		arg.Username,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.Appearance,
		arg.IsPublished,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, username, display_name, bio, avatar_url, appearance, is_published, created_at, updated_at FROM profiles WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Appearance,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedProfileByUsername = `-- name: GetPublishedProfileByUsername :one
SELECT id, user_id, username, display_name, bio, avatar_url, appearance, is_published, created_at, updated_at FROM profiles WHERE username = $1 AND is_published = true
`

func (q *Queries) GetPublishedProfileByUsername(ctx context.Context, username string) (Profile, error) {
	row := q.db.QueryRow(ctx, getPublishedProfileByUsername, username)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.Appearance,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const profileUsernameExists = `-- name: ProfileUsernameExists :one
SELECT EXISTS (SELECT 1 FROM profiles WHERE username = $1 AND id <> $2)
`

type ProfileUsernameExistsParams struct {
	Username string    `json:"username"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) ProfileUsernameExists(ctx context.Context, arg ProfileUsernameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, profileUsernameExists, arg.Username, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE profiles
SET username = $2, display_name = $3, bio = $4, avatar_url = $5,
    appearance = $6, is_published = $7, updated_at = $8
WHERE id = $1
`

type UpdateProfileParams struct {
	ID          uuid.UUID `json:"id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
	Bio         string    `json:"bio"`
	AvatarUrl   string    `json:"avatar_url"`
	Appearance  []byte    `json:"appearance"`
	IsPublished bool      `json:"is_published"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.Appearance,
		arg.IsPublished,
		arg.UpdatedAt,
	)
	return err
}
